name: first CI workflow
on: push

branches:
  - main

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: open hello.txt file
        run: cat hello.txt